name: Run Tests on Push

on:
  push:
    branches: [ main ]  # uruchamiaj tylko przy pushu na main (możesz usunąć, jeśli chcesz wszystkie gałęzie)

jobs:
  test:
    runs-on: ubuntu-latest  # ✅ GitHub zapewnia maszynę do uruchomienia testów

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Run tests
        run: pytest -v
